/**
 * Collection of humorous taglines displayed on the welcome screen.
 *
 * {@link getRandomTagline} selects one at random each time the welcome
 * view mounts. Taglines are developer-culture jokes and editor in-jokes.
 */
export const taglines: string[] = [
  "A modern code editor",
  "Where bugs go to die",
  "Works on my machine™",
  "Just one more refactor",
  "git blame someone else",
  "printf debugging approved",
  "Built different (in Rust)",
  "Tab width: none of your business",
  "Ships code. Eventually.",
  "Bespoke code spelunking",
  "It's giving… IDE",
  "For the love of semicolons",
  "Ctrl+Z is a lifestyle",
  "The code writes itself (it doesn't)",
  "$ git commit -m 'fix'",
  "Stack Overflow, but faster",
  "404: work-life balance not found",
  "Your compiler's best friend",
  "Now with 20% fewer segfaults",
  "undefined is not a bug",
  "Technically it compiles",
  "rm -rf /node_modules && pray",
  "Have you tried turning it off and on again?",
  "It's not a bug, it's a feature",
  "Powered by caffeine and spite",
  "Your second favourite editor",
  "We have dark mode (obviously)",
  "Shipping bugs at the speed of light",
  "Brought to you by a sleep-deprived developer",
  "Type-safe, probably",
  "async/await for the soul",
  "// TODO: add more taglines",
  "segfault (core dumped)",
  "NaN out of 10 developers recommend",
  "sudo make me a sandwich",
  "merge conflicts not included",
  "git push --force (don't)",
  "0 days since last npm audit",
  "cargo build --release (please wait)",
  "Lovingly crafted by humans, allegedly",
  "Your therapist recommended this",
  "Less vim, more vibe",
  "Emacs users welcome (but concerned)",
  "VSCode refugees welcome",
  "No Copilot required",
  "Born in a terminal, raised in a browser",
  "Actually reads the error messages",
  "The IDE your IDE wants to be",
  "Making spaghetti code look beautiful",
  "Compiling… please stand by",
  "For developers who like to live dangerously",
  "100% organic, free-range code",
  "The last editor you'll ever need (until the next one)",
  "Batteries not included. node_modules are.",
  "Stack trace? More like stack novel",
  "Where console.log goes to shine",
  "One semicolon to rule them all",
  "Off by one error not included",
  "Ship it",
  "It builds locally",
  "In production, no one can hear you scream",
  "git init and pray",
  "Documentation? We don't do that here",
  "Comments are for quitters",
  "Linting: the voice in your head that won't shut up",
  "We don't talk about v0.0.1",
  "Refactoring is just rearranging deck chairs",
  "YOLO-driven development",
  "Now hiring: rubber duck",
  "Agile: we move the goalposts so you don't have to",
  "DELETE FROM todo_list WHERE done = false",
  "Hello, World!",
  "exit 0",
  ":wq",
  "^C",
  "throw new Error('not my problem')",
  "// this should not happen",
  "// I have no idea why this works",
  "catch (e) { /* ¯\\_(ツ)_/¯ */ }",
  "Making JavaScript slightly less painful",
  "Rust: because C++ wasn't scary enough",
  "undefined behaviour is a vibe",
  "Garbage collected, unlike my thoughts",
  "Null pointer? Barely know her",
  "The heap called, it's full",
  "Memory leaks are just long-term thinking",
  "Premature optimisation is the root of all evil",
  "Big O(h no)",
  "O(n²) problems",
  "Recursion: see recursion",
  "A monad is just a monoid in the category of endofunctors",
  "Write once, debug everywhere",
  "It works in staging",
  "Blame the intern",
  "The cloud is just someone else's computer",
  "Deploying at 4:59pm on a Friday",
  "One linter to rule them all",
  "Prettier? I barely know her",
  "ESLint said no",
  "TypeScript: making JavaScript feel something",
  "Type inference is your friend",
  "any is always the answer",
  "// eslint-disable-next-line",
  "@ts-ignore and pray",
  "Where import cycles go to flourish",
  "Side effects? What side effects?",
  "Pure functions, impure thoughts",
  "Referential transparency achieved",
  "Immutable data, mutable deadlines",
  "The bus factor is 1",
  "10x developer (of bugs)",
  "Senior developer: someone who's made more mistakes",
  "git log --oneline (sobbing)",
  "git stash pop (recklessly)",
  "Detached HEAD? Relatable",
  "Cherry-pick responsibly",
  "Rebase: the forbidden technique",
  "Your branch is 847 commits behind main",
  "Force push forgiveness, not permission",
  "No tests, no mercy",
  "Tests are just code that tests your patience",
  "100% test coverage (of the wrong things)",
  "TDD: Test Driven Despair",
  "CI/CD: Crying In / Crying Daily",
  "Docker: it works in the container",
  "Kubernetes: because one abstraction wasn't enough",
  "Microservices: distributing the blame",
  "Serverless: someone else's problem",
  "The database is probably fine",
  "SELECT * FROM problems",
  "N+1 queries? Bold strategy",
  "Indexes are for people who care",
  "Normalisation: overrated",
  "It's not a deadlock, it's a standoff",
  "Race conditions build character",
  "mutex my beloved",
  "Async all the way down",
  "Callback hell: now with async/await",
  "Promises were made",
  "Event loop trauma",
  "Maximum call stack exceeded (emotionally)",
  "Heap snapshot: don't look",
  "Profiling is just self-reflection for code",
  "Lighthouse score: 23",
  "Bundle size: eventually your problem",
  "Tree shaking the will to live",
  "webpack config: cursed artifact",
  "Vite: fast, unlike your backend",
  "Hot module replacement for the soul",
  "The DOM is not your friend",
  "innerHTML and we don't care",
  "z-index: 9999",
  "display: flex (and cry)",
  "It looks fine on my screen",
  "Mobile-first (lies)",
  "Responsive by accident",
  "Accessibility? Noted",
  "Semantic HTML is a myth",
  "Div soup, anyone?",
  "CSS: Cascading Style Suffering",
  "margin: auto (hoping for the best)",
  "!important considered harmful",
  "Dark mode: the only mode",
  "Light mode users need not apply",
  "fn main() { println!(\"help\"); }",
  "The borrow checker is always right",
  "Lifetime annotations: trust the process",
  "unsafe { /* here be dragons */ }",
  "cargo clippy --fix (a blessing)",
  "No GC, no problem",
  "Zero-cost abstractions, infinite-cost debugging",
  "Where null references come to die",
  "Option<hope>",
  "Result<sanity, Error>",
  "unwrap() and cope",
  "Match exhaustively or don't match at all",
  "Move semantics: no take-backs",
  "The borrower always pays",
  "impl Display for Frustration",
  "Vec<thought> is empty",
  "HashMap<desire, reality>",
  "Arc<Mutex<Sanity>>",
  "Box<dyn Problem>",
  "where T: Tired",
  "Fearless concurrency (terrified developer)",
  "Clippy has thoughts",
  "The type system is trying to help",
  "Compiler error E0502: overlapping borrows on your dreams",
  "Made with ❤️ and stack traces",
  "404: motivation not found",
  "Stands for nothing, ships for everything",
  "est. git init",
  "Offline-first, online-last",
  "Your keyboard deserves better",
  "Pair programming with yourself",
  "Single-threaded ambitions",
  "println! considered elegant",
  "The linter loves you (it just has a funny way of showing it)",
  "Every pixel placed with indifference",
  "Tabs. Final answer.",
  "Spaces. Just kidding. Tabs.",
  "Vim mode: coming eventually",
  "Opens instantly (the terminal does)",
  "No electron was harmed",
  "Lighter than VS Code by several pounds",
  "Memory usage: surprisingly reasonable",
  "The one with the good terminal",
  "More terminal, less configuration",
  "Commit early, commit often, commit regrets",
  "Your git history is a cry for help",
  "main is just a suggestion",
  "const correctness is a personality",
  "Monorepo survivor",
  "cargo test (fingers crossed)",
  "One weird trick to ship faster",
  "Buy low, sell high, deploy on Fridays",
  "If it's stupid but it works…",
  "First, do no harm. Then, ship.",
  "Don't panic (but maybe panic)",
  "Loading your existential dread…",
  "Compiles in release mode",
  "Indexed by anxiety",
  "Where WIP commits go to live",
  "Sponsored by no one, loved by someone",
];

export function getRandomTagline(): string {
  return taglines[Math.floor(Math.random() * taglines.length)];
}
